/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VaultsIndexRouteImport } from './routes/vaults.index'
import { Route as GroupIndexRouteImport } from './routes/group.index'
import { Route as VaultsVaultIdRouteImport } from './routes/vaults.$vaultId'
import { Route as GroupCreateRouteImport } from './routes/group.create'
import { Route as GroupVaultIdRouteImport } from './routes/group.$vaultId'

const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultsIndexRoute = VaultsIndexRouteImport.update({
  id: '/vaults/',
  path: '/vaults/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupIndexRoute = GroupIndexRouteImport.update({
  id: '/group/',
  path: '/group/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultsVaultIdRoute = VaultsVaultIdRouteImport.update({
  id: '/vaults/$vaultId',
  path: '/vaults/$vaultId',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupCreateRoute = GroupCreateRouteImport.update({
  id: '/group/create',
  path: '/group/create',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupVaultIdRoute = GroupVaultIdRouteImport.update({
  id: '/group/$vaultId',
  path: '/group/$vaultId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/history': typeof HistoryRoute
  '/group/$vaultId': typeof GroupVaultIdRoute
  '/group/create': typeof GroupCreateRoute
  '/vaults/$vaultId': typeof VaultsVaultIdRoute
  '/group/': typeof GroupIndexRoute
  '/vaults/': typeof VaultsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/history': typeof HistoryRoute
  '/group/$vaultId': typeof GroupVaultIdRoute
  '/group/create': typeof GroupCreateRoute
  '/vaults/$vaultId': typeof VaultsVaultIdRoute
  '/group': typeof GroupIndexRoute
  '/vaults': typeof VaultsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/history': typeof HistoryRoute
  '/group/$vaultId': typeof GroupVaultIdRoute
  '/group/create': typeof GroupCreateRoute
  '/vaults/$vaultId': typeof VaultsVaultIdRoute
  '/group/': typeof GroupIndexRoute
  '/vaults/': typeof VaultsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/history'
    | '/group/$vaultId'
    | '/group/create'
    | '/vaults/$vaultId'
    | '/group/'
    | '/vaults/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/history'
    | '/group/$vaultId'
    | '/group/create'
    | '/vaults/$vaultId'
    | '/group'
    | '/vaults'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/history'
    | '/group/$vaultId'
    | '/group/create'
    | '/vaults/$vaultId'
    | '/group/'
    | '/vaults/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  HistoryRoute: typeof HistoryRoute
  GroupVaultIdRoute: typeof GroupVaultIdRoute
  GroupCreateRoute: typeof GroupCreateRoute
  VaultsVaultIdRoute: typeof VaultsVaultIdRoute
  GroupIndexRoute: typeof GroupIndexRoute
  VaultsIndexRoute: typeof VaultsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaults/': {
      id: '/vaults/'
      path: '/vaults'
      fullPath: '/vaults/'
      preLoaderRoute: typeof VaultsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/': {
      id: '/group/'
      path: '/group'
      fullPath: '/group/'
      preLoaderRoute: typeof GroupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaults/$vaultId': {
      id: '/vaults/$vaultId'
      path: '/vaults/$vaultId'
      fullPath: '/vaults/$vaultId'
      preLoaderRoute: typeof VaultsVaultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/create': {
      id: '/group/create'
      path: '/group/create'
      fullPath: '/group/create'
      preLoaderRoute: typeof GroupCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/$vaultId': {
      id: '/group/$vaultId'
      path: '/group/$vaultId'
      fullPath: '/group/$vaultId'
      preLoaderRoute: typeof GroupVaultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  HistoryRoute: HistoryRoute,
  GroupVaultIdRoute: GroupVaultIdRoute,
  GroupCreateRoute: GroupCreateRoute,
  VaultsVaultIdRoute: VaultsVaultIdRoute,
  GroupIndexRoute: GroupIndexRoute,
  VaultsIndexRoute: VaultsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
