/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VaultsIndexRouteImport } from './routes/vaults.index'
import { Route as VaultsVaultIdRouteImport } from './routes/vaults.$vaultId'

const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultsIndexRoute = VaultsIndexRouteImport.update({
  id: '/vaults/',
  path: '/vaults/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultsVaultIdRoute = VaultsVaultIdRouteImport.update({
  id: '/vaults/$vaultId',
  path: '/vaults/$vaultId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/history': typeof HistoryRoute
  '/vaults/$vaultId': typeof VaultsVaultIdRoute
  '/vaults/': typeof VaultsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/history': typeof HistoryRoute
  '/vaults/$vaultId': typeof VaultsVaultIdRoute
  '/vaults': typeof VaultsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/history': typeof HistoryRoute
  '/vaults/$vaultId': typeof VaultsVaultIdRoute
  '/vaults/': typeof VaultsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create' | '/history' | '/vaults/$vaultId' | '/vaults/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create' | '/history' | '/vaults/$vaultId' | '/vaults'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/history'
    | '/vaults/$vaultId'
    | '/vaults/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  HistoryRoute: typeof HistoryRoute
  VaultsVaultIdRoute: typeof VaultsVaultIdRoute
  VaultsIndexRoute: typeof VaultsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaults/': {
      id: '/vaults/'
      path: '/vaults'
      fullPath: '/vaults/'
      preLoaderRoute: typeof VaultsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaults/$vaultId': {
      id: '/vaults/$vaultId'
      path: '/vaults/$vaultId'
      fullPath: '/vaults/$vaultId'
      preLoaderRoute: typeof VaultsVaultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  HistoryRoute: HistoryRoute,
  VaultsVaultIdRoute: VaultsVaultIdRoute,
  VaultsIndexRoute: VaultsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
